### ISSUE TITLE
Can't filter by tags with tag inheritance

### ISSUE THREAD

**Issue by tim-yao** [enkessler/cql#10]
Thanks for the nice tool first. I had an issue filtering by tags that seems a bug to me.

As we can use the tag inheritance feature (https://cucumber.io/docs/cucumber/api/#tag-inheritance). Tags that are placed above a Feature will be inherited by Scenario, Scenario Outline, or Examples. Like below:

```
@tag_1
Feature: A test feature

        Scenario: Test 1
          * some steps
  
        @special_tag
        Scenario: Test 2
          * some other steps
          * some other steps
          * some other steps
 ```

In my query:
```
total_tests = cql_repo.query do
  select name
  from scenarios
  with tags '@tag_1'
end
```

it will get 0 scenarios. I expect it can get 2 scenarios.

**Comment by enkessler** [comment]
You appear to be using the predefined `tags` filter, which only looks at the tags that are directly on a model. The `all_tags` attribute is what you'd want to check if you want to include both direct and indirect tags. There is no predefined filter for that, so you'd just use an arbitrary filter block like this:

```Ruby
total_tests = cql_repo.query do
  select name
  from scenarios
  with { |scenario| scenario.all_tags.map(&:name).include?('@tag_1') }
end
```

**Comment by tim-yao** [comment]
Appreciate your help @enkessler! The above works for me. 
For making it work as expected, I need some idea how to get Scenario outline examples name?
```
@tag_1
Feature: A test feature

        Scenario Outline: Test 1
          * some steps
  
        @special_tag
        Examples: Test 2
            | foo |
```
With
```
total_tests = cql_repo.query do
  select name
  from scenarios, examples
  with { |scenario| scenario.all_tags.map(&:name).include?('@tag_1') }
  with { |example| example.all_tags.map(&:name).include?('@tag_1') }
end
pp total_tests
```
I couldn't get `name` of the `examples/scenario outlines` like what I can get from `scenarios`. 
I will get:
```
[{"name"=>""}]
```
Not sure where I can find those data structures, that may help me to figure it out without too many questions.
Thanks again in advance!

**Comment by enkessler** [comment]
What you should be getting (and what I'm getting when I run that code) is:
```
[{"name"=>"Test 2"}]
```

`[{"name"=>""}]` is a very strange thing to get, given the sample Gherkin, because it suggests
  1. That the model has a `name` attribute and
  2. That that attribute is `''` or `nil`

Although `Example` models having a `name` attribute is expected, all of the namable models in your sample Gherkin have names, so none of them should ever end up with `''` or `nil` as their `name` value.

> Not sure where I can find those data structures, that may help me to figure it out without too many questions.

All queries are done against a tree of [models](https://github.com/enkessler/cuke_modeler#cukemodeler). The CQL DSL is just a more convenient way to investigate that model tree without having to write a bunch of loops and conditionals to walk through the model tree yourself. To see what kinds of models are available and what attributes they have, you can look [here](https://www.rubydoc.info/gems/cuke_modeler).

> I couldn't get `name` of the `examples/scenario outlines` like what I can get from `scenarios`.

You'll want to have a look at how the [DSL clauses](https://github.com/enkessler/cql/tree/master/testing/cucumber/features/clauses) work. In particular, the '[from](https://github.com/enkessler/cql/blob/master/testing/cucumber/features/clauses/from_clause.feature)' and '[with](https://github.com/enkessler/cql/blob/master/testing/cucumber/features/clauses/with_clause.feature)' clauses. 

With your sample query, you are getting only one result because there is only one `CukeModeler::Example` in the model tree for your sample Gherkin and there are no `CukeModeler::Scenario` models. Scenario outlines have a different model class. So your 'from' clause needs to be `from outlines, examples`.

Also, your 'with' clauses are redundant. The name of the variable in the filter block has no impact on anything, so you have essentially written

```
with { |foo| foo.all_tags.map(&:name).include?('@tag_1') }
with { |foo| foo.all_tags.map(&:name).include?('@tag_1') }
```

If you want to have different filters for different types of model, you'll want to use [targeted filters](https://github.com/enkessler/cql/blob/b34e68d2bfec08d700c1d780fc58fa25667d6cb2/testing/cucumber/features/clauses/with_clause.feature#L130) like this

```
with scenarios => lambda { |foo| foo.all_tags.map(&:name).include?('@tag_1') }
with examples => lambda { |foo| foo.all_tags.map(&:name).include?('@special_tag') }
```

**Comment by tim-yao** [comment]
Appreciate your time and patience @enkessler.
Sorry was busy with other work and didn't get back to you earlier. It looks like I have a lot to look at above, and I will find some time to figure out the cause. Thanks!

**Comment by enkessler** [comment]
No worries. I appreciate knowing that someone actually uses the things that I make.
