### ISSUE TITLE
Great tool! Couple of points.

### ISSUE THREAD

**Issue by jfstephe** [enkessler/cql#7]
Hi,
First off. Thanks for doing this, it's a great tool!! A couple of minor points, really just to document them, rather than expecting a fix.
1. The readme examples are incorrect - they refer to 'gs' rather than the CQL::Repository object
2. I couldn't seem to get 'basic_tag' (found in the specs you have) to work. Does the test actually pass?

Once again. Many thanks, this should be shipped with all cucumber varieties!!

John

**Comment by enkessler** [comment]
Good news: The most current version of the gem has been released and available for about a year.
Bad news: I completely forgot to push the latest code back to GitHub for about a year.

The Readme has been updated and the 'basic_tag' spec has been removed. If I recall correctly, that was the one spec that I could never get to pass when I took over the project and I believe it was because that particular functionality was never implemented.

If your enthusiasm holds and you are still in the mood to review the gem, feel free to do just that and let me know of any other feedback that you may have.
